#pragma once

//GLFW
#define FPL_MOUSE_BUTTON_1         0
#define FPL_MOUSE_BUTTON_2         1
#define FPL_MOUSE_BUTTON_3         2
#define FPL_MOUSE_BUTTON_4         3
#define FPL_MOUSE_BUTTON_5         4
#define FPL_MOUSE_BUTTON_6         5
#define FPL_MOUSE_BUTTON_7         6
#define FPL_MOUSE_BUTTON_8         7
#define FPL_MOUSE_BUTTON_LAST      FPL_MOUSE_BUTTON_8
#define FPL_MOUSE_BUTTON_LEFT      FPL_MOUSE_BUTTON_1
#define FPL_MOUSE_BUTTON_RIGHT     FPL_MOUSE_BUTTON_2
#define FPL_MOUSE_BUTTON_MIDDLE    FPL_MOUSE_BUTTON_3