#pragma once

#include "FraplesSeven/Core/Core.h"
//------------For Sandbox---------------//
#include "FraplesSeven/Core/App.h"
#include "FraplesSeven/Core/Layer.h"
#include "FraplesSeven/Core/Log.h"
#include "FraplesSeven/ImGui/imGuiLayer.h"
#include "FraplesSeven/Core/Input.h"
#include "FraplesSeven/Core/MouseButtonCodes.h"
#include "FraplesSeven/Core/KeyCode.h"	 
#include "FraplesSeven/Core/TimeSteps.h"
#include "glm/gtc/matrix_transform.hpp"
//------------Renderer---------------//
#include "FraplesSeven/Renderer/Renderer.h"
#include "FraplesSeven/Renderer/Renderer2D.h"
#include "FraplesSeven/Renderer/RenderCommands.h"
#include "FraplesSeven/Renderer/Buffer.h"
#include "FraplesSeven/Renderer/Shader.h"
#include "FraplesSeven/Renderer/FrameBuffer.h"
#include "FraplesSeven/Renderer/Texture.h"
#include "FraplesSeven/Renderer/SubTexture2D.h"
#include "FraplesSeven/Renderer/VertexArray.h"
#include "FraplesSeven/Renderer/OrthographicCamera.h"
#include "FraplesSeven/Renderer/OrthographicCameraController.h"
#include "FraplesSeven/Scene/Component.h"
#include "FraplesSeven/Scene/Scene.h"
#include "FraplesSeven/Scene/Entity.h"
#include "FraplesSeven/Scene/ScriptableEntity.h"

